# Generated by Django 5.2.8 on 2025-11-09 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PRD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(default='', max_length=200)),
                ('owner', models.CharField(default='', max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'In Review'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('target_release', models.DateField(blank=True, null=True)),
                ('problem_statement', models.TextField(blank=True, default='')),
                ('customer_pain_points', models.JSONField(blank=True, default=list)),
                ('supporting_data', models.JSONField(blank=True, default=list)),
                ('goals', models.JSONField(blank=True, default=list)),
                ('key_results', models.TextField(blank=True, default='')),
                ('functional_requirements', models.JSONField(blank=True, default=list)),
                ('metrics', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
